# TODO: https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-rust

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Rust setup
        uses: ./.github/actions/setup-rust
      - name: Run formatting check
        run: cargo make fmt-check
      - name: Run clippy check
        run: cargo make clippy-check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["cli-utils", "cli-forgo"]
    steps:
      - name: Rust setup
        uses: ./.github/actions/setup-rust
      - name: Run tests for ${{ matrix.project }}
        env:
          PROJECT: ${{ matrix.project }}
        run: cargo make test-project
