name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["forgo_lib_cli", "forgo"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rust setup
        uses: ./.github/actions/setup-rust
      - name: Run formatting check
        run: cargo make fmt-check-project ${{ matrix.project }}
      - name: Run clippy check
        run: cargo make clippy-check-project ${{ matrix.project }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["forgo_lib_cli", "forgo"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Rust setup
        uses: ./.github/actions/setup-rust
      - name: Run tests for ${{ matrix.project }}
        run: cargo make test-project ${{ matrix.project }}
