name: Release

on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: "Select project to release"
        required: true
        default: forgo
        options: &valid-projects
          - forgo
          - forgo-lib-cli
      version:
        description: "Version (e.g., 1.0.0)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust

      - name: Validate version aligns with package version
        run: test "$(toml get -r crates/${{ github.event.inputs.project }}/Cargo.toml package.version)" = "${{ github.event.inputs.version }}"

      - name: Validate version is semantic
        run: sem-tool validate "${{ github.event.inputs.version }}"

      - name: Build ${{ github.event.inputs.project }} in release mode
        run: cargo build --release -p ${{ github.event.inputs.project }}

      - name: Login into crates.io
        run: cargo login

      - name: "Package for crates.io"
        run: cargo package

      - name: "Publish ${{ github.event.inputs.project }} to crates.io"
        run: cargo publish -p ${{ github.event.inputs.project }}

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ github.event.inputs.project }}/${{ github.event.inputs.version }}"
          TITLE="${TAG}"
          gh release create "${TAG}" --title "${TITLE}" --generate-notes
        shell: bash
